name: bioenv_x86
channels:
  - defaults
  - bioconda
  - conda-forge
dependencies:
  - python=3.10
  - seaborn
  - matplotlib
  - numpy
  - biopython
  - pip
  - hmmer
  - clustalo
  - pandas
  - flask
  - requests
