name: bioenv_x86
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - seaborn
  - matplotlib
  - numpy
  - biopython
  - pandas
  - flask
  - requests
  - pip
  - clustalo
  - hmmer
